name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore API_em_Csharp/API_em_Csharp.csproj

    - name: Build
      run: dotnet build API_em_Csharp/API_em_Csharp.csproj --no-restore

    - name: Test
      run: dotnet test API_em_Csharp/API_em_Csharp.csproj --no-build --verbosity normal
